### PR TITLE
Upgrade rollup plugins

### PR DESCRIPTION
**Pull request by vladimyr**
This PR swaps deprecated plugins with new official variants:
1. `rollup-plugin-buble` => `@rolllup/plugin-buble`
2. `rollup-plugin-json` => `@rollup/plugin-json`

This is stacked onto #259

### CODE REVIEW

**Comment by vladimyr** [comment]
@fi3ework Hm, care to share why did you close it?

**Comment by fi3ework** [comment]
@vladimyr Hi, this PR bumps `@rolllup/plugin-buble` and `@rollup/plugin-json`. These two plugins had been upgraded in https://github.com/egoist/bili/pull/357. And #259 is still opened.

**Comment by vladimyr** [comment]
Ah missed that bit, thanks for the explanation 👍, hopefully, #259 lands soon.

**Comment by fi3ework** [comment]
@vladimyr I should close it with leaving a reason 😅.

**Comment by vladimyr** [comment]
Kill it with fire if you like 😛 I was just interested in giving some love to this awesome project which is by far the best rollup wrapper out there. Seeing someone else, actually, the man himself did it still warms my heart 😉

**Pull request closed without merging**
